#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/bakito/adguardhome-sync
  # -- image tag
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [adguardhome-sync documentation](https://adguardhome-sync.org/docs).
# @default -- See below
env:
  ORIGIN_URL: 'https://192.168.1.2:3000'
  ORIGIN_USERNAME: 'username'
  ORIGIN_PASSWORD: 'password'
  REPLICA_URL: 'http://192.168.1.3'
  # REPLICA_USERNAME: 'username'
  # REPLICA_PASSWORD: 'password'
  # REPLICA1_URL: 'http://192.168.1.4'
  # REPLICA1_USERNAME: 'username'
  # REPLICA1_PASSWORD: 'password'
  # REPLICA1_APIPATH: '/some/path/control'
  # REPLICA1_AUTOSETUP: true # if true, AdGuardHome is automatically initialized.
  # REPLICA1_INTERFACENAME: 'ens18' # use custom dhcp interface name
  CRON: '*/10 * * * *' # run every 10 minutes
  RUNONSTART: true
  # Configure sync features; by default all features are enabled.
  # FEATURES_GENERALSETTINGS: true
  # FEATURES_QUERYLOGCONFIG: true
  # FEATURES_STATSCONFIG: true
  # FEATURES_CLIENTSETTINGS: true
  # FEATURES_SERVICES: true
  # FEATURES_FILTERS: true
  # FEATURES_DHCP_SERVERCONFIG: true
  # FEATURES_DHCP_STATICLEASES: true
  # FEATURES_DNS_SERVERCONFIG: true
  # FEATURES_DNS_ACCESSLISTS: true
  # FEATURES_DNS_REWRITES: true

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence: {}
  # data:
  #   enabled: false
  #   mountPath: /data

args: ["run"]